### ISSUE TITLE
Ottimizzazione Inventory

### ISSUE THREAD

**Issue by Armilio** [Armilio/ATC9_ACE#13]
Da qui:

https://github.com/Armilio/ATC9_ACE/issues/6#issuecomment-386485575

Lo scopo è di sostituire/stravolgere le fnc dell'ATC (fatte originariamente da Encode):

https://github.com/Armilio/ATC9_ACE/blob/master/functions/weapons/fnc_addGears.sqf
https://github.com/Armilio/ATC9_ACE/blob/master/functions/weapons/fnc_getBasicLoadout.sqf
https://github.com/Armilio/ATC9_ACE/blob/master/functions/weapons/fnc_saveCurrentGears.sqf (da vedere se viene tenuta)

con fnc della BIS sperando che siano più solide. Nuova branch è richiesta. Fare riferimento a questa issue quando si apre nuova pull request (basta copiare l'url).

Doc:
https://community.bistudio.com/wiki/BIS_fnc_saveInventory
https://community.bistudio.com/wiki/BIS_fnc_loadInventory

**Comment by NikLoc** [comment]
In realtà @Armilio penso che il problema non sussista per via che proprio il rifleman AT respawna sempre con un arma nuova per cui avrebbe senso dargli almeno sempre una munizione nel launcher. Non sarebbe molto lineare spawnare la prima volta con il missile e poi, mi viene dato un launcher differente, e mi tocca andare alle casse.

Creerò altre classi, in questo istante stavo valutando una soluzione per l' UID.

**Comment by Armilio** [comment]
@NikLoc 

Una cosa utile per il Virtual Arsenal.

**Comment by Armilio** [comment]
@NikLoc 
Non so se ti può essere utile, ma ci sono tre opzioni per il respawnonstart:

respawnOnStart      = -1;      // 1: Respawn on start. Run respawn script on start. Available only for
                               //    INSTANT and BASE respawn types.
                               // 0: Don't respawn on start. Run respawn script on start. Available only for
                               //    INSTANT and BASE respawn types.
                               // -1: Don't respawn on start. Don't run respawn script on start.
