### ISSUE TITLE
Timer conquista in caso di "settore contestato"

### ISSUE THREAD

**Issue by Nemesi-BDR** [Armilio/ATC9_ACE#23]
In determinate situazioni e cioè numero difensori basso (es 4 o meno, oppure qualsiasi numero, da pensarci) e numero attaccanti grande es maggiore del doppio (da definire/valutare bene) il settore diventa in qualche modo contestato vale a dire scatta un timer. Se in un tempo x da valutare la situazione non cambia a favore dei difensori il settore viene conquistato dagli attaccanti allo scadere del tempo. Nel caso in cui nel frattempo si arrivi alla fine della partita, la fine partita sarebbe sospesa fino allo scadere del timer, dopodichè finisce registrando la situazione come si è creata. 
Risolverebbe alcune situazioni tra cui quella descritta da @FlipperLivorno e da correlare con la proposta di rivedere i numeri per la conquista del settore.

**Comment by Armilio** [comment]
Bisognerebbe modificare il sectorChecker e l'InitServer per il delay di fine partita.

**Comment by Armilio** [comment]
Direi che anche per questa cosa del contestato dopo fine partita sarebbe meglio riportare a 120 minuti il tempo di gioco.

**Comment by Armilio** [comment]
Fatto e testato

**Comment by Nemesi-BDR** [comment]
Proposta: sostituire contested con disputed:
"To strive to gain or win; struggle over: The two countries disputed the region for decades."

**Comment by Armilio** [comment]
Fatto.
