### ISSUE TITLE
Aggiornare NoVehCrateFill.sqf per loadout heli

### ISSUE THREAD

**Issue by Armilio** [Armilio/ATC9_ACE#30]
[BoxammoRheli2, "ATC_HELI_ATTACK_O"] call ace_rearm_fnc_addVehicleMagazinesToSupply;

ace_rearm_fnc_addVehicleMagazinesToSupply potrebbe non funziona granché bene con loadout, e non va più bene quel classname.

**Comment by Nemesi-BDR** [comment]
This functions wraps ace_rearm_fnc_addMagazineToSupply and uses it to add all default magazines of all supported turrets of the vehicle to the ammo truck.
Non è esattamente quello che vogliamo se no ci lasciavamo il camion RT_logi no?

**Comment by Nemesi-BDR** [comment]
Il classname ovviamente va cambiato. Testata la funzione, funziona bene anche col loadout, nel senso che carica solo quello che è stato messo nei piloni inizialmente. Riarma apparentemente in maniera illimitata però. Esattamente come il camion RT logi.

**Comment by Nemesi-BDR** [comment]
Non è questione del dynamic loadout fa lo stesso anche col merkava, riarma solo se impostato su munizioni infinite non specifici caricatori.

**Comment by Armilio** [comment]
Son sicuro che funziona con munizioni limitate visto che l'anno scorso c'erano munizioni limitate, ci darò una occhiata io.

**Comment by Armilio** [comment]
Chiuso per noia
