### ISSUE TITLE
Sector_checker: evitare "settore neutro"

### ISSUE THREAD

**Issue by Nemesi-BDR** [Armilio/ATC9_ACE#34]
Bisogna evitare che il settore sia neutro (grigio): il settore conteso non deve cambiare colore finchè la contesa non è finita. Stessa logica che si usa per i settori abbandonati, non cambiano colore finchè non sono conquistati. Non ci sono settori neutri. Quando il settore è conteso viene l'hint e al limite si può mettere un marker tipo ! ma non cambiare colore. Non ci sono settori neutri e ciò evita che non ci siano vincitori alla fine.

**Comment by Nemesi-BDR** [comment]
Non ricordo al momento quanto dura la contesa

**Comment by Armilio** [comment]
Non esiste nessun settore neutro, chiudo.

**Comment by Nemesi-BDR** [comment]
Occorre chiarire il comportamento (colore del settore) nel fine-partita.

**Comment by Nemesi-BDR** [comment]
Alla fine vengono conteggiati i settori rossi e blu. Se c'è un eventuale settore grigio come si comporta?

**Comment by Nemesi-BDR** [comment]
Non deve scattare la contestazione se non c'è tempo sufficiente a risolverla. E' così?
